package bot.commands.weapon

object ParentWeapon {
    const val NAGANT = "Nagant M1895"
    const val LEBEL = "Lebel 1886"
    const val MARTINI_HENRY = "Martini-Henry IC1"
    const val MOSIN_NAGANT = "Mosin-Nagant M1891"
    const val NIRTO_EXPRESS = "Nitro Express Rifle"
    const val ROMERO = "Romero 77"
    const val SPARKS_LRR = "Sparks LRR"
    const val SPECTER = "Specter 1882"
    const val SPRINGFIELD = "Springfield 1866"
    const val VETTERLI = "Vetterli 71 Karabiner"
    const val WINFIELD_TERMINUS = "Winfield 1887 Terminus"
    const val WINFIELD = "Winfield M1873"
    const val WINFIELD_C = "Winfield M1873C"
    const val WINFIELD_CENTENNIAL = "Winfield M1876 Centennial"
    const val BOMB_LANCE = "Bomb Lance"
    const val CALDWELL_RIVAL = "Caldwell Rival 78"
    const val CROSSBOW = "Crossbow"
    const val CROWN_N_KING = "Crown & King Auto-5"
    const val BORNHEIM = "Bornheim No. 3"
    const val AXE = "Combat Axe"
    const val DOLCH = "Dolch 96"
    const val CALDWELL_CONVERSION = "Caldwell Conversion"
    const val CALDWELL_PAX = "Caldwell Pax"
    const val CAVALRY_SABER = "Cavalry Saber"
    const val LEMAT = "LeMat Mark II Revolver"
    const val MACHETE = "Machete"
}