package bot.commands.weapon

object Version {
    const val SNIPER = "Sniper"
    const val MARKSMAN = "Marksman"
    const val DEADEYE = "Deadeye"
    const val TALON = "Talon"
    const val RIPOSTE = "Riposte"
    const val BAYONET = "Bayonet"
    const val AVTOMAT = "Avtomat"
    const val OFFICER = "Officer"
    const val CARBINE = "Carbine"
    const val SILENCER = "Silencer"
    const val MUSKET = "Musket"
    const val APERTURE = "Aperture"
    const val SWIFT = "Swift"
    const val MATCH = "Match"
    const val HANDCANNON = "Handcannon"
    const val PRECISION = "Precision"
    const val OBREZ = "Obrez"
    const val DRUM = "Drum"
    const val MACE = "Mace"
    const val HATCHET = "Hatchet"
    const val COMPACT = "Compact"
    const val STRIKER = "Striker"
    const val VANDAL = "Vandal"
    const val EXTENDED = "Extended"
    const val CHAIN_PISTOL = "Chain Pistol"
    const val PISTOL = "Pistol"
    const val UPPERCUT = "Uppercut"
    const val CLAW = "Claw"
    const val HAND = "Hand"
    const val BRAWLER = "Brawler"
}